
require('ui/base');
require('ui/header')(2);
require('docs');


var _ = require('underscore');
var underscore_render = __inline('../ui/item/item.tmpl');

var html1 = underscore_render({
    title: 'Generated by underscore template'
});

var template = require('arttemplate');
var arttemplate_render = __inline('../ui/item/item.atpl');

var html2 = arttemplate_render({
    title: 'Generated by artTemplate'
});

$('.row').html(html1 + html2);

//dialog
var dialog = require('dialog/dialog-plus');


dialog({
    title: 'dialog',
    content: 'first dialog'
}).show();